%RUN_SUPP_ROBUSTNESS  Supplementary Figure S4 — robustness of the low-speed weakening.
%   Port of code/run_supp_robustness.py. Reads only precomputed summaries:
%     data_matlab/supp_khip_sweep.csv    (run_khip_sweep_extended.m)
%     data_matlab/sens_beta_summary.csv  (run_beta_summary.m)
%     data_matlab/supp_csweep.csv        (run_csweep_extended.m)
%   Writes figures_matlab/fig_supp_robustness.{png,pdf,tiff}
%   Panels: (a) N_1/2 at s = 0.010 against k_hip; (b) the transition speed and its
%   bracket against k_hip; (c) N_1/2 at s = 0.040 against foot mass, with the three
%   larger foot masses named rather than plotted; (d) N_1/2 against speed for the
%   four push-off coefficients.
here = fileparts(mfilename('fullpath'));
datadir = fullfile(here, '..', 'data_matlab');
figdir  = fullfile(here, '..', 'figures_matlab');
if ~exist(figdir, 'dir'), mkdir(figdir); end

ksw  = readtable(fullfile(datadir, 'supp_khip_sweep.csv'));
csw  = readtable(fullfile(datadir, 'supp_csweep.csv'));

f = figure('Units', 'inches', 'Position', [1 1 9.4 7.0], 'Color', 'w');
set(f, 'DefaultAxesFontSize', 9.5, 'DefaultTextFontSize', 9.5);
G = [0.92 0.92 0.92];

% ---- (a) hip-spring coefficient: half-life at the common slowest step length ----
ax = subplot(2, 2, 1); hold(ax, 'on');
ks = unique(ksw.k_hip);
% Compare at a COMMON REALISED step length, not at a common q. The nine branches
% share the q grid, but their realised step lengths at q = 0.010 span 2.4%
% (0.009794 to 0.010029), so an exact match on s = 0.010 would either find
% nothing or, if s were rounded, silently compare nine different gaits.
s_common = -Inf;
for i = 1:numel(ks)
    s_common = max(s_common, min(ksw.s(abs(ksw.k_hip - ks(i)) < 1e-9)));
end
n_at_smin = zeros(size(ks));
for i = 1:numel(ks)
    m = abs(ksw.k_hip - ks(i)) < 1e-9;
    [sr, o] = sort(ksw.s(m)); nh = ksw.N_half(m); nh = nh(o);
    good = isfinite(nh);
    n_at_smin(i) = interp1(sr(good), nh(good), s_common, 'linear');
end
fprintf('  panel (a): common realised step length s = %.6f\n', s_common);
semilogy(ax, ks, n_at_smin, 'o-', 'Color', [0 0 0], 'MarkerSize', 5, 'LineWidth', 1.4, ...
         'MarkerFaceColor', [0 0 0], 'DisplayName', '$N_{1/2}$ at a common realised $s$, each branch');
set(ax, 'YScale', 'log');
xline(ax, -0.16, ':', 'Color', [0.6 0.6 0.6], 'LineWidth', 1.1, 'HandleVisibility', 'off');
[~, i16] = min(abs(ks + 0.16));
text(ax, ks(i16), n_at_smin(i16), sprintf('  main branch, $N_{1/2}=%.1f$', n_at_smin(i16)), 'Interpreter', 'latex', ...
     'FontSize', 8, 'Color', [0.3 0.3 0.3], 'VerticalAlignment', 'bottom');
xlabel(ax, '$k_{\mathrm{hip}}$', 'Interpreter', 'latex');
ylabel(ax, sprintf('$N_{1/2}$ at $s=%.4f$ (steps)', s_common), 'Interpreter', 'latex');
ylim(ax, [300 1600]);
title(ax, '(a) hip-spring coefficient', 'FontSize', 10, 'FontWeight', 'normal');
 ax.TitleHorizontalAlignment = 'left';
legend(ax, 'Interpreter', 'latex', 'FontSize', 7.6, 'Box', 'off', 'Location', 'northeast');
grid(ax, 'on'); ax.GridColor = G; ax.GridAlpha = 1; ax.LineWidth = 0.4; box(ax, 'off');

% ---- (b) transition speed against k_hip: bracket midpoint and width ----
ax = subplot(2, 2, 2); hold(ax, 'on');
mid = nan(size(ks)); halfw = nan(size(ks));
for i = 1:numel(ks)
    m = abs(ksw.k_hip - ks(i)) < 1e-9;
    vv = ksw.v(m); im = ksw.lam1_im(m);
    cx = vv(im ~= 0); re_ = vv(im == 0);
    if ~isempty(cx) && ~isempty(re_)
        hi = min(cx); lo = max(re_(re_ < hi));
        if ~isempty(lo), mid(i) = 0.5 * (lo + hi); halfw(i) = 0.5 * (hi - lo); end
    end
end
errorbar(ax, ks, mid, halfw, 's-', 'Color', [0 0 0], 'MarkerSize', 5, 'LineWidth', 1.4, ...
         'CapSize', 2.5, 'MarkerFaceColor', [0 0 0]);
xline(ax, -0.16, ':', 'Color', [0.6 0.6 0.6], 'LineWidth', 1.1);
text(ax, -0.16, max(mid, [], 'omitnan'), ' main branch', 'FontSize', 8, 'Color', [0.35 0.35 0.35], ...
     'VerticalAlignment', 'top');
xlabel(ax, '$k_{\mathrm{hip}}$', 'Interpreter', 'latex');
ylabel(ax, 'transition speed $v^{*}$', 'Interpreter', 'latex');
title(ax, '(b) where the mode switch occurs', 'FontSize', 10, 'FontWeight', 'normal');
 ax.TitleHorizontalAlignment = 'left';
grid(ax, 'on'); ax.GridColor = G; ax.GridAlpha = 1; ax.LineWidth = 0.4; box(ax, 'off');

% ---- (c) small finite foot mass ----
ax = subplot(2, 2, 3); hold(ax, 'on');
% Compare at a COMMON REALISED step length, as in panel (a). The four branches
% share the q grid but not a realised s: at q = 0.040 the realised step lengths
% span 23.2% (0.032081 to 0.039523). The realised geometry per branch is in
% data_matlab/a5_beta_realised.csv, generated by run_beta_realised.m;
% interpolate each branch to the largest per-branch minimum.
br = readtable(fullfile(datadir, 'a5_beta_realised.csv'));
bb = unique(br.beta);
s_common_b = -Inf;
for i = 1:numel(bb)
    s_common_b = max(s_common_b, min(br.s_real(abs(br.beta - bb(i)) < 1e-9)));
end
% Match run_beta_realised.m: nudge up and round to 6 decimals (-> 0.039524).
s_common_b = round(s_common_b + 1e-6, 6);
bn = zeros(size(bb));
for i = 1:numel(bb)
    m = abs(br.beta - bb(i)) < 1e-9;
    [sr, o] = sort(br.s_real(m)); nh = br.N_half(m); nh = nh(o);
    good = isfinite(nh);
    bn(i) = interp1(sr(good), nh(good), s_common_b, 'linear');
end
fprintf('  panel (c): common realised step length s = %.6f\n', s_common_b);
fprintf('  panel (c): N_half = %s\n', mat2str(round(bn(:)'*100)/100));
plot(ax, bb, bn, '^-', 'Color', [0 0 0], 'MarkerSize', 6, 'LineWidth', 1.4, ...
     'MarkerFaceColor', [0 0 0], 'DisplayName', sprintf('$N_{1/2}$ at the common realised $s=%.4f$', s_common_b));
xlim(ax, [-0.01 0.16]); ylim(ax, [0 170]);
xlabel(ax, 'foot mass $\beta$', 'Interpreter', 'latex');
ylabel(ax, '$N_{1/2}$ (steps)', 'Interpreter', 'latex');
title(ax, '(c) small finite foot mass', 'FontSize', 10, 'FontWeight', 'normal');
 ax.TitleHorizontalAlignment = 'left';
legend(ax, 'Interpreter', 'latex', 'FontSize', 7.8, 'Box', 'off', 'Location', 'northwest');
grid(ax, 'on'); ax.GridColor = G; ax.GridAlpha = 1; ax.LineWidth = 0.4; box(ax, 'off');

% ---- (d) push-off coefficient ----
ax = subplot(2, 2, 4); hold(ax, 'on');
CS  = [0.80 1.00 1.04 1.20];
COL = [0 0 0; 0.35 0.35 0.35; 0 0 0; 0.5 0.5 0.5];
LSs = {'-', '--', '-', ':'};
LW  = [1.3 1.4 2.4 1.7];
for i = 1:numel(CS)
    m = abs(csw.c - CS(i)) < 1e-9;
    [vv, o] = sort(csw.v(m)); nn = csw.N_half(m); nn = nn(o);
    if CS(i) == 1.04, lbl = sprintf('$c=%.2f$  (main)', CS(i)); else, lbl = sprintf('$c=%.2f$', CS(i)); end
    semilogy(ax, vv, nn, LSs{i}, 'Color', COL(i, :), 'LineWidth', LW(i), 'DisplayName', lbl);
end
set(ax, 'YScale', 'log');
xlim(ax, [0 0.235]); ylim(ax, [1 1500]);
xlabel(ax, 'dimensionless speed $v$', 'Interpreter', 'latex');
ylabel(ax, '$N_{1/2}$ (steps)', 'Interpreter', 'latex');
title(ax, '(d) push-off coefficient in $P(q)=c\,\alpha_p\tan\alpha_p$', 'Interpreter', 'latex', ...
      'FontSize', 10, 'FontWeight', 'normal');
ax.TitleHorizontalAlignment = 'left';
legend(ax, 'Interpreter', 'latex', 'FontSize', 8, 'Box', 'off', 'Location', 'northeast');
grid(ax, 'on'); ax.GridColor = G; ax.GridAlpha = 1; ax.LineWidth = 0.4; box(ax, 'off');

base = fullfile(figdir, 'fig_supp_robustness');
exportgraphics(f, [base '.png'], 'Resolution', 300);
exportgraphics(f, [base '.pdf'], 'ContentType', 'vector');
exportgraphics(f, [base '.tiff'], 'Resolution', 300);
close(f);
fprintf('saved: %s.{png,pdf,tiff}\n', base);
